# 与抬头显示(HUD)相关的选项。
# 这些选项在保存后将自动更新。
[hud]

	[hud.general]
		# 如果启用，当玩家遭受"寒冷饥饿"效果（次要温度效果）时，食物饱和度将在食物条上显示。
		"Show Food Saturation Bar" = false
		# 是否渲染食物条和水分条的原始动画。数值越低，条抖动得越厉害。
		# 本模组将渲染一个新的食物条，作为寒冷温度的次要效果。
		# 如果启用了温度次要效果，请禁用此动画，以便与其他渲染食物条的模组兼容（例如Appleskin）。
		"Show Vanilla Bar Animation Overlay" = false

	[hud.temperature]
		# 温度的显示方式。可接受的值如下：
		#    SYMBOL - 在快捷栏上方以符号显示玩家当前温度。
		#    NONE - 禁用温度指示器。
		#Allowed Values: SYMBOL, NONE
		"Temperature Display Mode" = "SYMBOL"
		# 温度指示器的X和Y偏移量。将两者都设置为0则表示无偏移。
		#Range: -10000 ~ 10000
		"Temperature Display X Offset" = 0
		#Range: -10000 ~ 10000
		"Temperature Display Y Offset" = -6
		# 当温度计作为饰物装备时（需要curios模组），显示的体温指示器的X和Y偏移量。
		# 将两者都设置为0则表示无偏移。
		#Range: -10000 ~ 10000
		"Body Temperature Display X Offset" = 0
		#Range: -10000 ~ 10000
		"Body Temperature Display Y Offset" = 0
		# 如果启用，玩家在高温时会看到雾状效果。
		"Heat Temperature Overlay" = true
		# 如果启用，玩家在低温时会看到霜冻效果。
		"Cold Temperature Overlay" = true
		# 如果启用，玩家在面临恶劣温度时可以听到呼吸声。
		"Breathing Sound Enabled" = true
		# 低于此温度阈值时，玩家会渲染出冷呼吸效果。-1000则禁用此功能。
		#Range: -1000.0 ~ 1000.0
		"Cold Breath Temperature Threshold" = 10.0
		# 如果启用，以华氏度显示温度值。
		"Temperature In Fahrenheit" = false

		[hud.temperature.wetness]
			# 湿度指示器的X和Y偏移量。将两者都设置为0则表示无偏移。
			#Range: -10000 ~ 10000
			"Wetness Indicator X Offset" = 0
			#Range: -10000 ~ 10000
			"Wetness Indicator Y Offset" = 0

[body-damage]
	# 身体损伤指示器的X和Y偏移量。将两者都设置为0则表示无偏移。
	# 默认情况下，在物品栏旁边渲染。
	#Range: -10000 ~ 10000
	"Body Damage Indicator X Offset" = 0
	#Range: -10000 ~ 10000
	"Body Damage Indicator Y Offset" = 0
	# 身体损伤指示器渲染的肢体生命值阈值。
	# 如果设置为1.1，则始终渲染身体损伤指示器。
	# 如果设置为1.0，则只要肢体受伤就会渲染身体损伤指示器。
	#Range: 0.0 ~ 1.1
	"Body Damage Indicator Limb Health Threshold" = 1.0

[season-cards]
	# 季节卡片的X和Y偏移量。将两者都设置为0则表示无偏移。
	# 默认情况下，在垂直方向顶部四分之一处且水平居中的位置渲染。
	#Range: -10000 ~ 10000
	"Season Cards Display X Offset" = 0
	#Range: -10000 ~ 10000
	"Season Cards Display Y Offset" = 0
	# 在玩家首次生成或玩家维度更改后，渲染季节卡片前的延迟时间（以游戏刻计）。
	#Range: > 0
	"Season Cards Delay In Ticks" = 80
	# 季节卡片完全渲染的显示时间（以游戏刻计）。
	#Range: > 0
	"Season Cards Display Time In Ticks" = 40
	# 季节卡片出现时的淡入时间（以游戏刻计）。
	#Range: > 0
	"Season Cards Fade in In Ticks" = 20
	# 季节卡片消失时的淡出时间（以游戏刻计）。
	#Range: > 0
	"Season Cards Fade Out In Ticks" = 20

[thirst]
	# 是否显示水分饱和度。
	"Render the hydration saturation" = true
	# 如果启用，当水分过低时玩家的视野会变得模糊。
	"Low Hydration Effect" = true

	[thirst.tooltip]
		# 如果启用，在物品提示框中显示水分值。
		"Show Hydration Tooltip" = true
		# 如果启用，在提示框中将水分和饱和度值显示在同一行。
		"Merge Hydration And Saturation Tooltip" = true

	[thirst.hydration-bar]
		# 如果启用，将显示水分条。
		"Show Hydration Bar" = true
		# 如果启用，当玩家手持可饮用物品时，将在水分条上显示预览效果。
		"Show Drink Preview" = true
		# 水分条向右移动的距离。
		#Range: -10000 ~ 10000
		"Hydration Bar Offset X" = 0
		# 水分条向下移动的距离。
		#Range: -10000 ~ 10000
		"Hydration Bar Offset Y" = 0
		# 如果启用，将显示水分消耗（水分条后面的灰色条）。
		"Render the hydration exhaustion" = true

[health-overhaul]
	# 如果启用，将尝试将破碎之心和护盾之心附加到生命条的末尾。
	# 与 overflowing-bars 模组进行了兼容。
	"Append Broken/Shield Hearts To Health Bar" = true