
#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

	[types.wood_type]

		[types.wood_type.createdieselgenerators]
			chip_wood = true

		[types.wood_type.tfc]
			acacia = true
			ash = true
			aspen = true
			birch = true
			blackwood = true
			chestnut = true
			douglas_fir = true
			hickory = true
			kapok = true
			mangrove = true
			maple = true
			oak = true
			palm = true
			pine = true
			rosewood = true
			sequoia = true
			spruce = true
			sycamore = true
			white_cedar = true
			willow = true

		[types.wood_type.afc]
			baobab = true
			eucalyptus = true
			mahogany = true
			hevea = true
			tualang = true
			teak = true
			cypress = true
			fig = true
			ironwood = true
			ipe = true

		[types.wood_type.ad_astra]
			aeronos = false
			strophar = false
			glacian = false

		[types.wood_type.valhelsia_structures]
			lapidified_jungle = true

		[types.wood_type.vinery]
			dark_cherry = false

		[types.wood_type.born_in_chaos_v1]
			scorched = true

		[types.wood_type.alexscaves]
			pewen = false
			thornwood = false

		[types.wood_type.eidolon]
			illwood = true

	[types.leaves_type]

		[types.leaves_type.ad_astra]
			glacian = true

		[types.leaves_type.vinery]
			grapevine = true
			dark_cherry = true
			apple = true

		[types.leaves_type.alexscaves]
			ancient = true

		[types.leaves_type.eidolon]
			illwood = true

#Disables specific entries
[entries]

	[entries.wood_type]

		[entries.wood_type.handcrafted]
			counter = true
			corner_trim = true
			fancy_bed = true
			desk = true
			shelf = true
			cupboard = true
			dining_bench = true
			bench = true
			drawer = true
			pillar_trim = true
			side_table = true
			nightstand = true
			couch = true
			table = true
			chair = true

		[entries.wood_type.functionalstorage]
			1 = false
			4 = false
			2 = false

		[entries.wood_type.refurbished_furniture]
			storage_cabinet = true
			storage_jar = true
			kitchen_cabinetry = true
			crate = true
			desk = true
			chair = true
			light_ceiling_fan = true
			cutting_board = true
			drawer = true
			table = true
			mail_box = true
			dark_ceiling_fan = true
			kitchen_sink = true
			toilet = true
			lattice_fence = true
			basin = true
			kitchen_drawer = true
			lattice_fence_gate = true
			bath = true
			kitchen_storage_cabinet = true

		[entries.wood_type.valhelsia_structures]
			bundled_posts = true
			post = true
			bundled_stripped_posts = true
			stripped_post = true
			cut_post = true
			cut_stripped_post = true

		[entries.wood_type.valhelsia_furniture]
			stool = true
			hay_chair = true
			chair = true
			table = true
			desk_drawer = true
			desk = true

		[entries.wood_type.create]
			window_pane = true
			window = true

		[entries.wood_type.farmersdelight]
			cabinet = false

		[entries.wood_type.workshop_for_handsome_adventurer]
			dual_table_bottom_left = true
			tool_rack_double = true
			potion_shelf = true
			book_shelf_minimal = true
			simple_table = true
			book_shelf_open_double = true
			tool_rack_framed = true
			tool_rack_single = true
			book_shelf_double = true
			book_shelf_open_minimal = true
			dual_table_top_right = true
			dual_table_top_left = true
			tool_rack_pframed = true
			book_shelf_with_lanterns = true
			dual_table_bottom_right = true
			workstation_placer = true

	[entries.leaves_type]

		[entries.leaves_type.refurbished_furniture]
			hedge = false

