
[ShieldList]
	#
	#List of items to considered as shields, any item with right-click functionality will theoretically work
	#Automatically populated with items that have parrying stats set by active datapacks
	shieldList = ["immersiveeng ineering:shield", "alexscaves:resistor_shield", "endermanoverhaul:corrupted_shield", "tfc:metal/shield/bismuth_bronze", "tfc:metal/shield/red_steel", "tfc:metal/shield/blue_steel", "tfc:metal/shield/black_steel", "tfc:metal/shield/steel", "tfc:metal/shield/copper", "tfc:metal/shield/bronze", "tfc:metal/shield/black_bronze", "shieldexp:wooden_shield", "shieldexp:iron_shield", "shieldexp:netherite_shield", "alexsmobs:shield_of_the_deep", "minecraft:shield", "tfc:metal/shield/wrought_iron", "shieldexp:golden_shield", "shieldexp:diamond_shield", "artifacts:umbrella", "immersiveengineering:shield", "kubejs:blue_steel_greatsword", "kubejs:bronze_greatsword", "spartanweaponry:netherite_greatsword", "spartanweaponry:nickel_greatsword", "kubejs:steel_greatsword", "spartanweaponry:platinum_greatsword", "spartanweaponry:stone_greatsword", "kubejs:red_steel_greatsword", "kubejs:copper_greatsword", "kubejs:black_bronze_greatsword", "spartanweaponry:electrum_greatsword", "spartanweaponry:steel_greatsword", "spartanweaponry:tin_greatsword", "kubejs:black_steel_greatsword", "spartanweaponry:diamond_greatsword", "spartanweaponry:bronze_greatsword", "spartanweaponry:silver_greatsword", "kubejs:bismuth_bronze_greatsword", "spartanweaponry:lead_greatsword", "spartanweaponry:golden_greatsword", "kubejs:wrought_iron_greatsword", "spartanweaponry:aluminum_greatsword", "spartanweaponry:iron_greatsword", "spartanweaponry:constantan_greatsword", "spartanweaponry:invar_greatsword", "spartanweaponry:wooden_greatsword", "spartanweaponry:copper_greatsword"]
	#
	#List of items to not consider as shields, even if they have stats set by a datapack
	shieldBlacklist = []

[Modifiers]
	#
	#Disable the cooldown when the player lowers their shield
	noLoweringCooldown = false
	#
	#Disable putting shields on cooldown at all
	noCooldown = false
	#
	#Make all shields have vanilla movement speed
	noSpeedModifier = false
	#
	#Make shields only block partial damage from explosions when not parrying
	harderExplosions = false
	#
	#Double the parry window for a more relaxed experience
	lenientParryMode = false
	#
	#Double the shield stamina for a more relaxed experience
	lenientStaminaMode = false

